<a href="https://colab.research.google.com/github/yurin-l/test/blob/master/ml%EC%8B%A4%EC%8A%B55_multilayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [4]:
# 1.과거의 데이터를 준비한다
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [5]:
# 독립변수, 종속변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [6]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [11]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [7]:
# 3. 데이터로 모델을 학습(fit)합니다.
model.fit(독립, 종속, epochs=1000,verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 19.1134
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 18.2221
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 20.2730
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 18.2611
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 19.4152
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 18.9241
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 19.6802
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 17.5955
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 19.0214
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 18.0728


In [12]:
# 4. 모델을 이용합니다.
model.predict(독립[0:5])
print(종속[0:5])

   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [10]:
# 모델의 수식 확인
model.get_weights()

[array([[-1.34229437e-01, -1.85107738e-02,  3.43970060e-01,
         -3.62967588e-02, -3.02456439e-01, -4.74652141e-01,
         -4.87679662e-03,  2.14625858e-02,  4.45561171e-01,
         -3.24258916e-02],
        [ 1.89482927e-01, -1.61159765e-02,  4.34515834e-01,
          7.53311813e-02, -3.00073344e-02, -6.77097917e-01,
          1.16504088e-01, -9.76784900e-02, -4.06503856e-01,
         -5.83871938e-02],
        [ 5.77692986e-01, -4.15485963e-04, -5.66711724e-01,
         -5.54919429e-02,  4.79258507e-01,  1.01568252e-01,
          1.72064304e-02,  8.44560117e-02,  1.83691859e-01,
         -2.06054822e-01],
        [-2.65801579e-01, -1.19660616e+00, -3.07547878e-02,
          1.57664764e+00, -2.60593462e+00,  1.85356522e+00,
          1.38917935e+00, -1.10861194e+00, -2.70600438e-01,
          1.58065462e+00],
        [ 3.55848104e-01, -6.81043148e-01, -1.86609998e-01,
         -2.70356119e-01, -4.02501598e-02,  8.51151049e-02,
         -1.31825492e-01, -3.00576955e-01,  2.299225

아이리스 품종 분류

In [13]:
# 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [21]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy')

In [22]:
# 3. 데이터로 모델을 학습(fit)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 3ms/step - loss: 1.4717
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 1.3348
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 1.3585
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.2236
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 1.2429
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1782
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 1.1524
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 1.1333
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 1.1078
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0809
Epoch 11/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0742
Epoch 12/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0814
Epoch 13/100
5/5 [==============================] - 0s 2ms/st

In [23]:
# 4. 모델을 이용합니다
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.92295146e-01 7.65054347e-03 5.43391216e-05]
 [9.87579763e-01 1.22943623e-02 1.25863153e-04]
 [9.88938808e-01 1.09513160e-02 1.09882334e-04]
 [9.84301150e-01 1.55276498e-02 1.71252279e-04]
 [9.92251813e-01 7.69392587e-03 5.42942726e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
